# action.yml

name: 'Code-Turtle AI Code Review'
description: 'An AI-powered code reviewer that analyzes pull requests and provides feedback.'
author: 'Richard Joseph'

inputs:
  pr_number:
    description: 'The number of the pull request to review.'
    required: true
  model_url:
    description: 'URL of the GGUF model to download for the review.'
    required: false
    default: 'https://huggingface.co/QuantFactory/Meta-Llama-3-8B-Instruct-GGUF/resolve/main/Meta-Llama-3-8B-Instruct.Q4_K_M.gguf'
  github_token:
    description: 'The GitHub token for posting comments.'
    required: true
  repository:
    description: 'The owner and repository name (e.g., octocat/Hello-World).'
    required: true

runs:
  using: 'docker'
  image: 'docker://ghcr.io/richard-m-j/llama-cpp:main'
  env:
    MODEL_URL: ${{ inputs.model_url }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
    PR_NUMBER: ${{ inputs.pr_number }}
    GH_REPO: ${{ inputs.repository }}
  entrypoint: '/bin/bash'
  args:
    - entrypoint.sh