# .github/workflows/ai-review-caller.yml
# This workflow triggers the reusable code review workflow within the same repository.

name: Trigger AI Code Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  trigger-review:
    # Call the reusable workflow at the job level
    uses: ./.github/workflows/reusable-review.yml
    
    # Define permissions for the called workflow
    permissions:
      pull-requests: write
      
    # Pass inputs to the reusable workflow
    with:
      pr_number: ${{ github.event.pull_request.number }}
      base_sha: ${{ github.event.pull_request.base.sha }}
      head_sha: ${{ github.event.pull_request.head.sha }}
      
    # Pass secrets to the reusable workflow
    secrets: inherit