# .github/workflows/ai-review-caller.yml
# This workflow triggers the reusable code review workflow within the same repository.

name: Trigger AI Code Review

on:
  pull_request:
    branches: [ main ]

jobs:
  trigger-review:
    runs-on: ubuntu-latest
    
    # Grant permissions for the called workflow to write a PR comment.
    permissions:
      pull-requests: write
      
    steps:
      - name: Call the Reusable Review Workflow
        # Use a local path to call a reusable workflow in the same repository.
        uses: ./.github/workflows/reusable-review.yml
        with:
          pr_number: ${{ github.event.pull_request.number }}
          base_sha: ${{ github.event.pull_request.base.sha }}
          head_sha: ${{ github.event.pull_request.head.sha }}
        # 'secrets: inherit' is good practice to pass the GITHUB_TOKEN
        secrets: inherit