# .github/workflows/ai-review-caller.yml
# This workflow triggers the reusable code review workflow within the same repository.

name: Trigger AI Code Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  trigger-review:
    uses: Richard-m-j/code-turtle/.github/workflows/reusable-review.yml@main
    
    permissions:
      contents: read          # <-- Add this line
      pull-requests: write
      
    with:
      pr_number: ${{ github.event.pull_request.number }}
      base_sha: ${{ github.event.pull_request.base.sha }}
      head_sha: ${{ github.event.pull_request.head.sha }}
      
    secrets: inherit