# .github/workflows/ai-review-caller.yml
# This workflow triggers the reusable code review workflow within the same repository.

name: Trigger AI Code Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  generate-diff:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch all history for all branches and tags
          fetch-depth: 0

      - name: 2. Generate and Upload Diff as Artifact
        run: |
          git fetch origin ${{ github.event.pull_request.base.sha }}
          git fetch origin ${{ github.event.pull_request.head.sha }}
          git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > code.diff
      - uses: actions/upload-artifact@v4
        with:
          name: code-diff-artifact
          path: code.diff

  trigger-review:
    needs: generate-diff
    uses: ./.github/workflows/reusable-review.yml
    permissions:
      pull-requests: write
    with:
      pr_number: ${{ github.event.pull_request.number }}
    secrets: inherit