name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/**'

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [indexer, reviewer]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.service }}.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/code-turtle-${{ matrix.service }}:latest