name: code-turtle - Agentic Code Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write

jobs:
  code-review:
    runs-on: ubuntu-latest
    container:
      image: ${{ secrets.DOCKERHUB_USERNAME }}/code-turtle-reviewer:latest
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 2. Run the Review Workflow
        # FIX: Added the 'run' keyword to execute the script.
        # The script is located at /app, which is the WORKDIR in the Dockerfile.
        run: python /app/scripts/orchestrator.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          PINECONE_API_KEY: ${{ secrets.VECTOR_DB_API_KEY }}
          PINECONE_ENVIRONMENT: ${{ secrets.VECTOR_DB_ENVIRONMENT }}
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION_NAME: "us-east-1"