name: code-turtle - Agentic Code Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  code-review:
    runs-on: ubuntu-latest
    
    container:
      image: richardjoseph1/code-turtle-reviewer:latest

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # FIX: Add this step to resolve the "dubious ownership" error in Actions
      - name: 2. Mark Git Directory as Safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: 3. Run the Review Workflow
        run: python /app/scripts/orchestrator.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          PINECONE_API_KEY: ${{ secrets.VECTOR_DB_API_KEY }}
          PINECONE_ENVIRONMENT: ${{ secrets.VECTOR_DB_ENVIRONMENT }}
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION_NAME: "us-east-1"