name: code-turtle - Agentic Code Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write # Required to post comments on the PR

jobs:
  code-review:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4
        with:
          # Fetch full history to allow diffing between base and head
          fetch-depth: 0

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Install Dependencies
        run: pip install -r scripts/requirements.txt

      - name: 4. Run the Review Workflow
        env:
          # --- GitHub Context ---
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          
          # --- Vector DB Credentials ---
          PINECONE_API_KEY: ${{ secrets.VECTOR_DB_API_KEY }}
          PINECONE_ENVIRONMENT: ${{ secrets.VECTOR_DB_ENVIRONMENT }}
          
          # --- AWS Bedrock Credentials for LLM ---
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION_NAME: "us-east-1" # Or your preferred AWS region
        run: python scripts/orchestrator.py