name: Code-turtle Indexing Agent

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Triggers the workflow on push events to the main branch
  push:
    branches:
      - main

jobs:
  build-and-index:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: 3. Install Dependencies
        run: pip install -r scripts/requirements.txt

      - name: 4. Run the Indexing Agent
        run: python scripts/indexer.py
        env:
          PINECONE_API_KEY: ${{ secrets.VECTOR_DB_API_KEY }}
          PINECONE_ENVIRONMENT: ${{ secrets.VECTOR_DB_ENVIRONMENT }}
