name: Code-turtle Indexing Agent

on:
  # Triggers the workflow on push events for the main branch
  push:
    branches:
      - main

jobs:
  run-indexer:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the full repository to the runner's workspace
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Run the indexer container
      - name: Run Indexing Container
        run: |
          docker run --rm \
            -e PINECONE_API_KEY=${{ secrets.VECTOR_DB_API_KEY }} \
            -e PINECONE_ENVIRONMENT=${{ secrets.VECTOR_DB_ENVIRONMENT }} \
            -e SCAN_PATH="/source_code" \
            -v ${{ github.workspace }}:/source_code \
            ${{ secrets.DOCKERHUB_USERNAME }}/code-turtle-indexer:latest