name: Code-turtle Indexing Agent

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Triggers the workflow on push events to the main branch
  push:
    branches:
      - main

jobs:
  build-and-index:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Build Docker Image
        run: docker build -t code-turtle-indexer .

      - name: 3. Run Indexing Container
        run: |
          docker run --rm \
            -e PINECONE_API_KEY=${{ secrets.VECTOR_DB_API_KEY }} \
            -e PINECONE_ENVIRONMENT=${{ secrets.VECTOR_DB_ENVIRONMENT }} \
            -e SCAN_PATH="/source_code" \
            -v ${{ github.workspace }}:/source_code \
            code-turtle-indexer