name: Code-turtle Indexing Agent

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed

jobs:
  run-indexer:
    runs-on: ubuntu-latest
    steps:
      - name: Run Indexing Container
        run: |
          docker run --rm \
            -e PINECONE_API_KEY=${{ secrets.VECTOR_DB_API_KEY }} \
            -e PINECONE_ENVIRONMENT=${{ secrets.VECTOR_DB_ENVIRONMENT }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/code-turtle-indexer:latest