# .github/workflows/llama-cpp-inference.yml

name: Run Llama.cpp Inference on Push

on:
  push:
    branches:
      - '**'

jobs:
  run-inference:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Step 1: Install dependencies (CURL library added here)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget cmake libcurl4-openssl-dev

      # Step 2: Clone the llama.cpp repository
      - name: Clone llama.cpp repository
        run: |
          git clone https://github.com/ggerganov/llama.cpp.git
      
      # Step 3: Build llama.cpp using CMake
      - name: Build llama.cpp
        run: |
          cd llama.cpp
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release

      # Step 4: Download a small GGUF model
      - name: Download AI Model
        run: |
          mkdir -p ./llama.cpp/models
          MODEL_URL="https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/resolve/main/tinyllama-1.1B-chat-v1.0.Q2_K.gguf"
          wget -O ./llama.cpp/models/model.gguf "$MODEL_URL"
          
      # Step 5: Run inference with a simple prompt
      - name: Run Inference
        run: |
          cd llama.cpp
          ./build/bin/main \
            -m ./models/model.gguf \
            -p "Hi AI, what is your name?" \
            -n 64 \
            -ngl 0