# .github/workflows/reusable-review.yml

name: Reusable AI Code Review

on:
  workflow_call:
    inputs:
      pr_number:
        description: 'The number of the pull request'
        required: true
        type: number
      code_diff:
        description: 'The code diff string to be reviewed'
        required: true
        type: string

permissions:
  pull-requests: write

jobs:
  code-review:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    container: yusiwen/llama.cpp:latest
    env:
      MODEL_URL: 'https://huggingface.co/QuantFactory/Meta-Llama-3-8B-Instruct-GGUF/resolve/main/Meta-Llama-3-8B-Instruct.Q4_K_M.gguf'

    steps:
      - name: 1. Generate Model URL Hash
        id: model_hash
        run: echo "hash=$(echo -n '${{ env.MODEL_URL }}' | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT

      - name: 2. Cache AI Model
        id: cache-model
        uses: actions/cache@v4
        with:
          path: ./model.gguf
          # The primary key is specific, including the Git ref.
          key: ${{ runner.os }}-gguf-model-${{ steps.model_hash.outputs.hash }}-${{ github.ref }}
          # The restore key is a fallback that finds the latest cache with the same model hash, regardless of the branch.
          restore-keys: |
            ${{ runner.os }}-gguf-model-${{ steps.model_hash.outputs.hash }}-

      - name: 3. Download AI Model if not cached
        if: steps.cache-model.outputs.cache-hit != 'true'
        run: curl -L -o ./model.gguf "${{ env.MODEL_URL }}"

      - name: 4. Construct Prompt
        env:
          CODE_DIFF: ${{ inputs.code_diff }}
        run: |
          PROMPT_FILE="prompt.txt"
          SYSTEM_PROMPT="You are an expert code reviewer AI. Your task is to analyze the following code diff and provide concise, constructive feedback. Focus on potential bugs, logical errors, style violations, and areas for improved clarity or performance. Do not comment on trivial changes. Frame your feedback as helpful suggestions. Output your review in Markdown format."
          cat <<EOF > $PROMPT_FILE
          $SYSTEM_PROMPT

          Here is the code diff to review:
          \`\`\`diff
          $CODE_DIFF
          \`\`\`

          Please provide your review now.
          EOF

      - name: 5. Run LLM Inference
        env:
          LD_LIBRARY_PATH: /llama.cpp
        run: |
          echo "Starting LLM inference... This may take a few minutes."
          /llama.cpp/llama-cli \
            -m ./model.gguf \
            -f prompt.txt \
            --ctx-size 4096 \
            --n-predict 1024 \
            --temp 0.2 \
            > review_output.txt
          echo "LLM inference complete."

      - name: 6. Format and Post Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ inputs.pr_number }}
          GH_REPO: ${{ github.repository }}
        run: |
          apt-get update && apt-get install -y git gh
          
          {
            echo "### 🤖 AI Code Review"
            echo ""
            echo "Here are some suggestions based on the latest changes. Please treat these as pointers for consideration, not mandates."
            echo ""
            echo "---"
            echo ""
            cat review_output.txt
          } > final_comment.md

          gh pr comment $PR_NUMBER --repo $GH_REPO --body-file final_comment.md